# Project information
site_name: Stancona
site_url: https://stancona.org/
site_author: eminboydak.4160

# Repository
repo_name: eminboydak/stancona
repo_url: https://github.com/eminboydak/stancona

# Copyright
copyright: Copyright &copy; 2023 Stancona

# Configuration
theme:
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: deep purple
  font:
    text: Roboto
    code: Fira Code
  language: tr
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - navigation.top
    - navigation.footer

extra:
  social:
    - icon: fontawesome/brands/discord
      link: http://discord.stancona.org/

nav:
  - Ana Sayfa: index.md
  - Rehber:
    - Temel:
      - Balangıç Rehberi: rehber/temel/gw2-baslangic-rehberi.md
      - Yeni Oyuncu Rehberi: rehber/temel/gw2-yeni-oyuncu-rehberi.md
    - Raid:
      - Spirit Vale (W1):
        - Vale Guardian: rehber/raid/vale-guardian.md
        - Gorseval the Multifarious: rehber/raid/gorseval-the-multifarious.md
        - Sabetha the Saboteur: rehber/raid/sabetha-the-saboteur.md 
      - Salvation Pass (W2):
        - Slothasor: rehber/raid/slothasor.md
        - Bandit Trio: rehber/raid/bandit-trio.md
  - Lore: index.md
  - Sıkça Sorulan Sorular: sss.md

extra_javascript:
  - https://unpkg.com/armory-embeds@^0.x.x/armory-embeds.js