# Project information
site_name: Stancona
site_url: https://stancona.github.io/stancona/
site_author: Stancona
site_description: >-
  Stancona, Guild Wars 2 topluluğunu bir araya getirmek ve Türkçe kaynak oluşturmak
  için kurulmuş bir guilddir.
discord_url: http://discord.stancona.org/

# Repository
repo_name: stancona/stancona
repo_url: https://github.com/stancona/stancona

# Copyright
copyright: Copyright &copy; 2023 Stancona

# Configuration
theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: slate
      primary: deep purple
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Aydınlık moda geç
    - scheme: default
      primary: deep purple
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Karanlık moda geç

  font:
    text: Open Sans
    code: Fira Code
  language: tr
  # logo: assets/logo.png
  favicon: assets/favicon.png
  icon:
    logo: simple/dragonframe
  features:
    # - announce.dismiss
    - content.action.edit
    # - content.action.view
    # - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    # - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    # - navigation.indexes
    - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    # - navigation.tracking
    # - navigation.path
    # - search.highlight
    # - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

# Plugins
plugins:
  - search:
      lang: tr
  - minify:
      minify_html: true
  # - social

# Hooks

# Customization
extra:
  social:
    - icon: fontawesome/brands/discord
      link: http://discord.stancona.org/

# Extensions
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Ana Sayfa: index.md
  - Rehber:
    - Başlangıç Rehberi: rehber/gw2-baslangic-rehberi.md
    - Yeni Oyuncu Rehberi: rehber/gw2-yeni-oyuncu-rehberi.md
    - İpuçları ve Püf Noktalar: rehber/ipuclari-puf-noktalar.md
    - Ascended Ekipman Rehberi: rehber/ascended-ekipman-rehberi.md
    - Raid:
      - Spirit Vale:
        - Vale Guardian: rehber/raid/spirit-vale/vale-guardian.md
        - Spirit Woods: rehber/raid/spirit-vale/spirit-woods.md
        - Gorseval: rehber/raid/spirit-vale/gorseval.md
        - Sabetha: rehber/raid/spirit-vale/sabetha.md
      - Salvation Pass:
        - Slothasor: rehber/raid/salvation-pass/slothasor.md
        - Bandit Trio: rehber/raid/salvation-pass/bandit-trio.md
        - Matthias Gabrel: rehber/raid/salvation-pass/matthias-gabrel.md
      - Stronghold of Faithful:
        - Siege the Stronghold: rehber/raid/stronghold-faithful/siege-the-stronghold.md
        - Keep Construct: rehber/raid/stronghold-faithful/keep-construct.md
        - Twisted Castle: rehber/raid/stronghold-faithful/twisted-castle.md
        - Xera: rehber/raid/stronghold-faithful/xera.md
      - Bastion of the Penitent:
        - Cairn the Indomitable: rehber/raid/bastion-penitent/cairn-the-indomitable.md
        - Mursaat Overseer: rehber/raid/bastion-penitent/mursaat-overseer.md
        - Samarog: rehber/raid/bastion-penitent/samarog.md
        - Deimos: rehber/raid/bastion-penitent/deimos.md
      - Hall of Chains:
        - Soulless Horror: rehber/raid/hall-chains/soulless-horror.md
        - River of Soul: rehber/raid/hall-chains/river-of-souls.md
        - Statues of Grenth: rehber/raid/hall-chains/statues-of-grenth.md
        - Dhuum: rehber/raid/hall-chains/dhuum.md
      - Mythwright Gambit:
        - Conjured Amalgamate: rehber/raid/mythwright-gambit/conjured-amalgamate.md
        - Sorting & Appraisal: rehber/raid/mythwright-gambit/sorting-appraisal.md
        - Twin Largos: rehber/raid/mythwright-gambit/twin-largos.md
        - Qadim: rehber/raid/mythwright-gambit/qadim.md
      - The Key of Ahdashim:
        - Gates of Ahdashim: rehber/raid/key-ahdashim/gates-of-ahdashim.md
        - Cardian Adina: rehber/raid/key-ahdashim/cardinal-adina.md
        - Cardinal Sabir: rehber/raid/key-ahdashim/cardinal-sabir.md
        - Qadim the Peerless: rehber/raid/key-ahdashim/qadim-the-peerless.md
    - Festival:
      - Lunar New Year: rehber/festival/lunar-new-year.md
      - Super Adventure Festival: rehber/festival/super-adventure-festival.md
      - Dragon Bash: rehber/festival/dragon-bash.md
      - Festival of the Four Winds: rehber/festival/festival-of-the-four-winds.md
      - Halloween: rehber/festival/halloween.md
      - Wintersday: rehber/festival/wintersday.md
    - Eklenti:
      - ArcDPS: rehber/eklenti/arcdps.md
      - Blish HUD: rehber/eklenti/blish-hud.md
      - TacO: rehber/eklenti/taco.md
  - Sıkça Sorulan Sorular: sss.md

extra_javascript:
  - https://unpkg.com/armory-embeds@^0.x.x/armory-embeds.js
